---
- name: Restart Auditd
  service:
     name: auditd
     state: restarted
  listen: "restart auditd"

- name: Restart Fail2ban
  service:
     name: fail2ban
     state: restarted
  listen: "restart fail2ban"

- name: Restart Sysstat
  service:
     name: sysstat
     state: restarted
  listen: "restart sysstat"
